layout_spectrum: 0.6744681
typography_spectrum: 0.4106383
color:
  lightness: 0.6446809
  brandStrength: 0.6854023
  saturation: 0.4446808
  rhythmicContrast: 0.7553192
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Tom Page Photography
